name: Continuous Integration

on:
  push: 
    branches: 
      - main

jobs: 
  deploy:
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        
      - name: Use Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '14.*'
      
      - name: Install dependencies
        run: npm ci

      - name: Test application
        run: npm test

      - name: Build application
        run: npm run build
